steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fresh-gravity-226207/test:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fresh-gravity-226207/test:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - test-deployment
  - test=gcr.io/fresh-gravity-226207/test:$SHORT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'