version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install .
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - restore_cache:
          key: cloud-sdk-{{ checksum ".circleci/install-and-activate-google-cloud-sdk.sh" }}
      - run:
          name: Prepare Google Cloud SDK
          command: /bin/bash .circleci/install-and-activate-google-cloud-sdk.sh
      - save_cache:
          paths:
            - ~/google-cloud-sdk
          key: cloud-sdk-{{ checksum ".circleci/install-and-activate-google-cloud-sdk.sh" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

      - run:
          name: Deploy to App Engine
          command: ${HOME}/google-cloud-sdk/bin/gcloud app deploy
