version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout

      # Install & cache python dependencies
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      # Install and cache Google Cloud SDK
      - restore_cache:
          key: cloud-sdk-{{ checksum ".circleci/install-and-activate-google-cloud-sdk.sh" }}
      - run: /bin/bash .circleci/install-and-activate-google-cloud-sdk.sh
      - save_cache:
          paths:
            - ~/google-cloud-sdk
          key: cloud-sdk-{{ checksum ".circleci/install-and-activate-google-cloud-sdk.sh" }}

      # Deploy to Google App Engine
      - run: gcloud app deploy
